// Copyright 2022 - Fasten Health
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir401

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
)

// THIS FILE IS GENERATED BY https://github.com/fastenhealth/gofhir-models-gen
// PLEASE DO NOT EDIT BY HAND

// CoverageEligibilityResponse is documented here http://hl7.org/fhir/StructureDefinition/CoverageEligibilityResponse
// This resource provides eligibility and plan details from the processing of an CoverageEligibilityRequest resource.
type CoverageEligibilityResponse struct {
	Unknown           map[string]interface{}                 `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                                `bson:"id,omitempty" json:"id,omitempty"`
	Meta              *Meta                                  `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules     *string                                `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language          *string                                `bson:"language,omitempty" json:"language,omitempty"`
	Text              *Narrative                             `bson:"text,omitempty" json:"text,omitempty"`
	Contained         []jsontext.Value                       `bson:"contained,omitempty" json:"contained,omitempty"`
	Extension         []Extension                            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension                            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identifier        []Identifier                           `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Status            FinancialResourceStatusCodes           `bson:"status" json:"status"`
	Purpose           []EligibilityResponsePurpose           `bson:"purpose" json:"purpose"`
	Patient           Reference                              `bson:"patient" json:"patient"`
	ServicedDate      *string                                `bson:"servicedDate,omitempty" json:"servicedDate,omitempty"`
	ServicedPeriod    *Period                                `bson:"servicedPeriod,omitempty" json:"servicedPeriod,omitempty"`
	Created           string                                 `bson:"created" json:"created"`
	Requestor         *Reference                             `bson:"requestor,omitempty" json:"requestor,omitempty"`
	Request           Reference                              `bson:"request" json:"request"`
	Outcome           ClaimProcessingCodes                   `bson:"outcome" json:"outcome"`
	Disposition       *string                                `bson:"disposition,omitempty" json:"disposition,omitempty"`
	Insurer           Reference                              `bson:"insurer" json:"insurer"`
	Insurance         []CoverageEligibilityResponseInsurance `bson:"insurance,omitempty" json:"insurance,omitempty"`
	PreAuthRef        *string                                `bson:"preAuthRef,omitempty" json:"preAuthRef,omitempty"`
	Form              *CodeableConcept                       `bson:"form,omitempty" json:"form,omitempty"`
	Error             []CoverageEligibilityResponseError     `bson:"error,omitempty" json:"error,omitempty"`
}

// Financial instruments for reimbursement for the health care products and services.
// All insurance coverages for the patient which may be applicable for reimbursement, of the products and services listed in the claim, are typically provided in the claim to allow insurers to confirm the ordering of the insurance coverages relative to local 'coordination of benefit' rules. One coverage (and only one) with 'focal=true' is to be used in the adjudication of this claim. Coverages appearing before the focal Coverage in the list, and where 'subrogation=false', should provide a reference to the ClaimResponse containing the adjudication results of the prior claim.
type CoverageEligibilityResponseInsurance struct {
	Unknown           map[string]interface{}                     `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                                    `bson:"id,omitempty" json:"id,omitempty"`
	Extension         []Extension                                `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension                                `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Coverage          Reference                                  `bson:"coverage" json:"coverage"`
	Inforce           *Boolean                                   `bson:"inforce,omitempty" json:"inforce,omitempty"`
	BenefitPeriod     *Period                                    `bson:"benefitPeriod,omitempty" json:"benefitPeriod,omitempty"`
	Item              []CoverageEligibilityResponseInsuranceItem `bson:"item,omitempty" json:"item,omitempty"`
}

// Benefits and optionally current balances, and authorization details by category or service.
type CoverageEligibilityResponseInsuranceItem struct {
	Unknown                 map[string]interface{}                            `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                      *string                                           `bson:"id,omitempty" json:"id,omitempty"`
	Extension               []Extension                                       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension       []Extension                                       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Category                *CodeableConcept                                  `bson:"category,omitempty" json:"category,omitempty"`
	ProductOrService        *CodeableConcept                                  `bson:"productOrService,omitempty" json:"productOrService,omitempty"`
	Modifier                []CodeableConcept                                 `bson:"modifier,omitempty" json:"modifier,omitempty"`
	Provider                *Reference                                        `bson:"provider,omitempty" json:"provider,omitempty"`
	Excluded                *Boolean                                          `bson:"excluded,omitempty" json:"excluded,omitempty"`
	Name                    *string                                           `bson:"name,omitempty" json:"name,omitempty"`
	Description             *string                                           `bson:"description,omitempty" json:"description,omitempty"`
	Network                 *CodeableConcept                                  `bson:"network,omitempty" json:"network,omitempty"`
	Unit                    *CodeableConcept                                  `bson:"unit,omitempty" json:"unit,omitempty"`
	Term                    *CodeableConcept                                  `bson:"term,omitempty" json:"term,omitempty"`
	Benefit                 []CoverageEligibilityResponseInsuranceItemBenefit `bson:"benefit,omitempty" json:"benefit,omitempty"`
	AuthorizationRequired   *Boolean                                          `bson:"authorizationRequired,omitempty" json:"authorizationRequired,omitempty"`
	AuthorizationSupporting []CodeableConcept                                 `bson:"authorizationSupporting,omitempty" json:"authorizationSupporting,omitempty"`
	AuthorizationUrl        *string                                           `bson:"authorizationUrl,omitempty" json:"authorizationUrl,omitempty"`
}

// Benefits used to date.
type CoverageEligibilityResponseInsuranceItemBenefit struct {
	Unknown            map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                 *string                `bson:"id,omitempty" json:"id,omitempty"`
	Extension          []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension  []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Type               CodeableConcept        `bson:"type" json:"type"`
	AllowedUnsignedInt *int                   `bson:"allowedUnsignedInt,omitempty" json:"allowedUnsignedInt,omitempty"`
	AllowedString      *string                `bson:"allowedString,omitempty" json:"allowedString,omitempty"`
	AllowedMoney       *Money                 `bson:"allowedMoney,omitempty" json:"allowedMoney,omitempty"`
	UsedUnsignedInt    *int                   `bson:"usedUnsignedInt,omitempty" json:"usedUnsignedInt,omitempty"`
	UsedString         *string                `bson:"usedString,omitempty" json:"usedString,omitempty"`
	UsedMoney          *Money                 `bson:"usedMoney,omitempty" json:"usedMoney,omitempty"`
}

// Errors encountered during the processing of the request.
type CoverageEligibilityResponseError struct {
	Unknown           map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                `bson:"id,omitempty" json:"id,omitempty"`
	Extension         []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Code              CodeableConcept        `bson:"code" json:"code"`
}

// This function returns resource reference information (resourceType, *resourceId)
func (r CoverageEligibilityResponse) ResourceRef() (string, *string) {
	return "CoverageEligibilityResponse", r.Id
}

// This function returns resources that are embedded in the resource
func (r CoverageEligibilityResponse) ContainedResources() []jsontext.Value {
	return r.Contained
}

type OtherCoverageEligibilityResponse CoverageEligibilityResponse

// MarshalJSON marshals the given CoverageEligibilityResponse as JSON into a byte slice
// WARNING: must use a non-pointer receiver here, because non-pointer variables may not call this function otherwise
// See: https://groups.google.com/g/golang-nuts/c/gW53LC_ZC98
func (r CoverageEligibilityResponse) MarshalJSON() ([]byte, error) {
	if r.Unknown == nil {
		r.Unknown = make(map[string]any)
	}
	r.Unknown["resourceType"] = "CoverageEligibilityResponse"
	return v2.Marshal(OtherCoverageEligibilityResponse(r))
}

// UnmarshalCoverageEligibilityResponse unmarshals a CoverageEligibilityResponse.
func UnmarshalCoverageEligibilityResponse(b []byte) (CoverageEligibilityResponse, error) {
	var coverageEligibilityResponse CoverageEligibilityResponse
	if err := v2.Unmarshal(b, &coverageEligibilityResponse); err != nil {
		return coverageEligibilityResponse, err
	}
	return coverageEligibilityResponse, nil
}
