// Copyright 2022 - Fasten Health
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir401

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
)

// THIS FILE IS GENERATED BY https://github.com/fastenhealth/gofhir-models-gen
// PLEASE DO NOT EDIT BY HAND

// EvidenceVariable is documented here http://hl7.org/fhir/StructureDefinition/EvidenceVariable
// The EvidenceVariable resource describes a "PICO" element that knowledge (evidence, assertion, recommendation) is about.
type EvidenceVariable struct {
	Unknown           map[string]interface{}           `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                          `bson:"id,omitempty" json:"id,omitempty"`
	Meta              *Meta                            `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules     *string                          `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language          *string                          `bson:"language,omitempty" json:"language,omitempty"`
	Text              *Narrative                       `bson:"text,omitempty" json:"text,omitempty"`
	Contained         []jsontext.Value                 `bson:"contained,omitempty" json:"contained,omitempty"`
	Extension         []Extension                      `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension                      `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Url               *string                          `bson:"url,omitempty" json:"url,omitempty"`
	Identifier        []Identifier                     `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Version           *string                          `bson:"version,omitempty" json:"version,omitempty"`
	Name              *string                          `bson:"name,omitempty" json:"name,omitempty"`
	Title             *string                          `bson:"title,omitempty" json:"title,omitempty"`
	ShortTitle        *string                          `bson:"shortTitle,omitempty" json:"shortTitle,omitempty"`
	Subtitle          *string                          `bson:"subtitle,omitempty" json:"subtitle,omitempty"`
	Status            PublicationStatus                `bson:"status" json:"status"`
	Date              *string                          `bson:"date,omitempty" json:"date,omitempty"`
	Publisher         *string                          `bson:"publisher,omitempty" json:"publisher,omitempty"`
	Contact           []ContactDetail                  `bson:"contact,omitempty" json:"contact,omitempty"`
	Description       *string                          `bson:"description,omitempty" json:"description,omitempty"`
	Note              []Annotation                     `bson:"note,omitempty" json:"note,omitempty"`
	UseContext        []UsageContext                   `bson:"useContext,omitempty" json:"useContext,omitempty"`
	Jurisdiction      []CodeableConcept                `bson:"jurisdiction,omitempty" json:"jurisdiction,omitempty"`
	Copyright         *string                          `bson:"copyright,omitempty" json:"copyright,omitempty"`
	ApprovalDate      *string                          `bson:"approvalDate,omitempty" json:"approvalDate,omitempty"`
	LastReviewDate    *string                          `bson:"lastReviewDate,omitempty" json:"lastReviewDate,omitempty"`
	EffectivePeriod   *Period                          `bson:"effectivePeriod,omitempty" json:"effectivePeriod,omitempty"`
	Topic             []CodeableConcept                `bson:"topic,omitempty" json:"topic,omitempty"`
	Author            []ContactDetail                  `bson:"author,omitempty" json:"author,omitempty"`
	Editor            []ContactDetail                  `bson:"editor,omitempty" json:"editor,omitempty"`
	Reviewer          []ContactDetail                  `bson:"reviewer,omitempty" json:"reviewer,omitempty"`
	Endorser          []ContactDetail                  `bson:"endorser,omitempty" json:"endorser,omitempty"`
	RelatedArtifact   []RelatedArtifact                `bson:"relatedArtifact,omitempty" json:"relatedArtifact,omitempty"`
	Type              *EvidenceVariableType            `bson:"type,omitempty" json:"type,omitempty"`
	Characteristic    []EvidenceVariableCharacteristic `bson:"characteristic" json:"characteristic"`
}

// A characteristic that defines the members of the evidence element. Multiple characteristics are applied with "and" semantics.
// Characteristics can be defined flexibly to accommodate different use cases for membership criteria, ranging from simple codes, all the way to using an expression language to express the criteria.
type EvidenceVariableCharacteristic struct {
	Unknown                      map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                           *string                `bson:"id,omitempty" json:"id,omitempty"`
	Extension                    []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension            []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Description                  *string                `bson:"description,omitempty" json:"description,omitempty"`
	DefinitionReference          Reference              `bson:"definitionReference" json:"definitionReference"`
	DefinitionCanonical          string                 `bson:"definitionCanonical" json:"definitionCanonical"`
	DefinitionCodeableConcept    CodeableConcept        `bson:"definitionCodeableConcept" json:"definitionCodeableConcept"`
	DefinitionExpression         Expression             `bson:"definitionExpression" json:"definitionExpression"`
	DefinitionDataRequirement    DataRequirement        `bson:"definitionDataRequirement" json:"definitionDataRequirement"`
	DefinitionTriggerDefinition  TriggerDefinition      `bson:"definitionTriggerDefinition" json:"definitionTriggerDefinition"`
	UsageContext                 []UsageContext         `bson:"usageContext,omitempty" json:"usageContext,omitempty"`
	Exclude                      *Boolean               `bson:"exclude,omitempty" json:"exclude,omitempty"`
	ParticipantEffectiveDateTime *string                `bson:"participantEffectiveDateTime,omitempty" json:"participantEffectiveDateTime,omitempty"`
	ParticipantEffectivePeriod   *Period                `bson:"participantEffectivePeriod,omitempty" json:"participantEffectivePeriod,omitempty"`
	ParticipantEffectiveDuration *Duration              `bson:"participantEffectiveDuration,omitempty" json:"participantEffectiveDuration,omitempty"`
	ParticipantEffectiveTiming   *Timing                `bson:"participantEffectiveTiming,omitempty" json:"participantEffectiveTiming,omitempty"`
	TimeFromStart                *Duration              `bson:"timeFromStart,omitempty" json:"timeFromStart,omitempty"`
	GroupMeasure                 *GroupMeasure          `bson:"groupMeasure,omitempty" json:"groupMeasure,omitempty"`
}

// This function returns resource reference information (resourceType, *resourceId)
func (r EvidenceVariable) ResourceRef() (string, *string) {
	return "EvidenceVariable", r.Id
}

// This function returns resources that are embedded in the resource
func (r EvidenceVariable) ContainedResources() []jsontext.Value {
	return r.Contained
}

type OtherEvidenceVariable EvidenceVariable

// MarshalJSON marshals the given EvidenceVariable as JSON into a byte slice
// WARNING: must use a non-pointer receiver here, because non-pointer variables may not call this function otherwise
// See: https://groups.google.com/g/golang-nuts/c/gW53LC_ZC98
func (r EvidenceVariable) MarshalJSON() ([]byte, error) {
	if r.Unknown == nil {
		r.Unknown = make(map[string]any)
	}
	r.Unknown["resourceType"] = "EvidenceVariable"
	return v2.Marshal(OtherEvidenceVariable(r))
}

// UnmarshalEvidenceVariable unmarshals a EvidenceVariable.
func UnmarshalEvidenceVariable(b []byte) (EvidenceVariable, error) {
	var evidenceVariable EvidenceVariable
	if err := v2.Unmarshal(b, &evidenceVariable); err != nil {
		return evidenceVariable, err
	}
	return evidenceVariable, nil
}
