// Copyright 2022 - Fasten Health
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir401

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
)

// THIS FILE IS GENERATED BY https://github.com/fastenhealth/gofhir-models-gen
// PLEASE DO NOT EDIT BY HAND

// FamilyMemberHistory is documented here http://hl7.org/fhir/StructureDefinition/FamilyMemberHistory
// Significant health conditions for a person related to the patient relevant in the context of care for the patient.
type FamilyMemberHistory struct {
	Unknown               map[string]interface{}         `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                    *string                        `bson:"id,omitempty" json:"id,omitempty"`
	Meta                  *Meta                          `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules         *string                        `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language              *string                        `bson:"language,omitempty" json:"language,omitempty"`
	Text                  *Narrative                     `bson:"text,omitempty" json:"text,omitempty"`
	Contained             []jsontext.Value               `bson:"contained,omitempty" json:"contained,omitempty"`
	Extension             []Extension                    `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension     []Extension                    `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identifier            []Identifier                   `bson:"identifier,omitempty" json:"identifier,omitempty"`
	InstantiatesCanonical []string                       `bson:"instantiatesCanonical,omitempty" json:"instantiatesCanonical,omitempty"`
	InstantiatesUri       []string                       `bson:"instantiatesUri,omitempty" json:"instantiatesUri,omitempty"`
	Status                FamilyHistoryStatus            `bson:"status" json:"status"`
	DataAbsentReason      *CodeableConcept               `bson:"dataAbsentReason,omitempty" json:"dataAbsentReason,omitempty"`
	Patient               Reference                      `bson:"patient" json:"patient"`
	Date                  *string                        `bson:"date,omitempty" json:"date,omitempty"`
	Name                  *string                        `bson:"name,omitempty" json:"name,omitempty"`
	Relationship          CodeableConcept                `bson:"relationship" json:"relationship"`
	Sex                   *CodeableConcept               `bson:"sex,omitempty" json:"sex,omitempty"`
	BornPeriod            *Period                        `bson:"bornPeriod,omitempty" json:"bornPeriod,omitempty"`
	BornDate              *string                        `bson:"bornDate,omitempty" json:"bornDate,omitempty"`
	BornString            *string                        `bson:"bornString,omitempty" json:"bornString,omitempty"`
	AgeAge                *Age                           `bson:"ageAge,omitempty" json:"ageAge,omitempty"`
	AgeRange              *Range                         `bson:"ageRange,omitempty" json:"ageRange,omitempty"`
	AgeString             *string                        `bson:"ageString,omitempty" json:"ageString,omitempty"`
	EstimatedAge          *Boolean                       `bson:"estimatedAge,omitempty" json:"estimatedAge,omitempty"`
	DeceasedBoolean       *Boolean                       `bson:"deceasedBoolean,omitempty" json:"deceasedBoolean,omitempty"`
	DeceasedAge           *Age                           `bson:"deceasedAge,omitempty" json:"deceasedAge,omitempty"`
	DeceasedRange         *Range                         `bson:"deceasedRange,omitempty" json:"deceasedRange,omitempty"`
	DeceasedDate          *string                        `bson:"deceasedDate,omitempty" json:"deceasedDate,omitempty"`
	DeceasedString        *string                        `bson:"deceasedString,omitempty" json:"deceasedString,omitempty"`
	ReasonCode            []CodeableConcept              `bson:"reasonCode,omitempty" json:"reasonCode,omitempty"`
	ReasonReference       []Reference                    `bson:"reasonReference,omitempty" json:"reasonReference,omitempty"`
	Note                  []Annotation                   `bson:"note,omitempty" json:"note,omitempty"`
	Condition             []FamilyMemberHistoryCondition `bson:"condition,omitempty" json:"condition,omitempty"`
}

// The significant Conditions (or condition) that the family member had. This is a repeating section to allow a system to represent more than one condition per resource, though there is nothing stopping multiple resources - one per condition.
type FamilyMemberHistoryCondition struct {
	Unknown            map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                 *string                `bson:"id,omitempty" json:"id,omitempty"`
	Extension          []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension  []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Code               CodeableConcept        `bson:"code" json:"code"`
	Outcome            *CodeableConcept       `bson:"outcome,omitempty" json:"outcome,omitempty"`
	ContributedToDeath *Boolean               `bson:"contributedToDeath,omitempty" json:"contributedToDeath,omitempty"`
	OnsetAge           *Age                   `bson:"onsetAge,omitempty" json:"onsetAge,omitempty"`
	OnsetRange         *Range                 `bson:"onsetRange,omitempty" json:"onsetRange,omitempty"`
	OnsetPeriod        *Period                `bson:"onsetPeriod,omitempty" json:"onsetPeriod,omitempty"`
	OnsetString        *string                `bson:"onsetString,omitempty" json:"onsetString,omitempty"`
	Note               []Annotation           `bson:"note,omitempty" json:"note,omitempty"`
}

// This function returns resource reference information (resourceType, *resourceId)
func (r FamilyMemberHistory) ResourceRef() (string, *string) {
	return "FamilyMemberHistory", r.Id
}

// This function returns resources that are embedded in the resource
func (r FamilyMemberHistory) ContainedResources() []jsontext.Value {
	return r.Contained
}

type OtherFamilyMemberHistory FamilyMemberHistory

// MarshalJSON marshals the given FamilyMemberHistory as JSON into a byte slice
// WARNING: must use a non-pointer receiver here, because non-pointer variables may not call this function otherwise
// See: https://groups.google.com/g/golang-nuts/c/gW53LC_ZC98
func (r FamilyMemberHistory) MarshalJSON() ([]byte, error) {
	if r.Unknown == nil {
		r.Unknown = make(map[string]any)
	}
	r.Unknown["resourceType"] = "FamilyMemberHistory"
	return v2.Marshal(OtherFamilyMemberHistory(r))
}

// UnmarshalFamilyMemberHistory unmarshals a FamilyMemberHistory.
func UnmarshalFamilyMemberHistory(b []byte) (FamilyMemberHistory, error) {
	var familyMemberHistory FamilyMemberHistory
	if err := v2.Unmarshal(b, &familyMemberHistory); err != nil {
		return familyMemberHistory, err
	}
	return familyMemberHistory, nil
}
