// Copyright 2022 - Fasten Health
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir401

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
)

// THIS FILE IS GENERATED BY https://github.com/fastenhealth/gofhir-models-gen
// PLEASE DO NOT EDIT BY HAND

// ImmunizationEvaluation is documented here http://hl7.org/fhir/StructureDefinition/ImmunizationEvaluation
// Describes a comparison of an immunization event against published recommendations to determine if the administration is "valid" in relation to those  recommendations.
type ImmunizationEvaluation struct {
	Unknown                map[string]interface{}            `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                     *string                           `bson:"id,omitempty" json:"id,omitempty"`
	Meta                   *Meta                             `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules          *string                           `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language               *string                           `bson:"language,omitempty" json:"language,omitempty"`
	Text                   *Narrative                        `bson:"text,omitempty" json:"text,omitempty"`
	Contained              []jsontext.Value                  `bson:"contained,omitempty" json:"contained,omitempty"`
	Extension              []Extension                       `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension      []Extension                       `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identifier             []Identifier                      `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Status                 ImmunizationEvaluationStatusCodes `bson:"status" json:"status"`
	Patient                Reference                         `bson:"patient" json:"patient"`
	Date                   *string                           `bson:"date,omitempty" json:"date,omitempty"`
	Authority              *Reference                        `bson:"authority,omitempty" json:"authority,omitempty"`
	TargetDisease          CodeableConcept                   `bson:"targetDisease" json:"targetDisease"`
	ImmunizationEvent      Reference                         `bson:"immunizationEvent" json:"immunizationEvent"`
	DoseStatus             CodeableConcept                   `bson:"doseStatus" json:"doseStatus"`
	DoseStatusReason       []CodeableConcept                 `bson:"doseStatusReason,omitempty" json:"doseStatusReason,omitempty"`
	Description            *string                           `bson:"description,omitempty" json:"description,omitempty"`
	Series                 *string                           `bson:"series,omitempty" json:"series,omitempty"`
	DoseNumberPositiveInt  *int                              `bson:"doseNumberPositiveInt,omitempty" json:"doseNumberPositiveInt,omitempty"`
	DoseNumberString       *string                           `bson:"doseNumberString,omitempty" json:"doseNumberString,omitempty"`
	SeriesDosesPositiveInt *int                              `bson:"seriesDosesPositiveInt,omitempty" json:"seriesDosesPositiveInt,omitempty"`
	SeriesDosesString      *string                           `bson:"seriesDosesString,omitempty" json:"seriesDosesString,omitempty"`
}

// This function returns resource reference information (resourceType, *resourceId)
func (r ImmunizationEvaluation) ResourceRef() (string, *string) {
	return "ImmunizationEvaluation", r.Id
}

// This function returns resources that are embedded in the resource
func (r ImmunizationEvaluation) ContainedResources() []jsontext.Value {
	return r.Contained
}

type OtherImmunizationEvaluation ImmunizationEvaluation

// MarshalJSON marshals the given ImmunizationEvaluation as JSON into a byte slice
// WARNING: must use a non-pointer receiver here, because non-pointer variables may not call this function otherwise
// See: https://groups.google.com/g/golang-nuts/c/gW53LC_ZC98
func (r ImmunizationEvaluation) MarshalJSON() ([]byte, error) {
	if r.Unknown == nil {
		r.Unknown = make(map[string]any)
	}
	r.Unknown["resourceType"] = "ImmunizationEvaluation"
	return v2.Marshal(OtherImmunizationEvaluation(r))
}

// UnmarshalImmunizationEvaluation unmarshals a ImmunizationEvaluation.
func UnmarshalImmunizationEvaluation(b []byte) (ImmunizationEvaluation, error) {
	var immunizationEvaluation ImmunizationEvaluation
	if err := v2.Unmarshal(b, &immunizationEvaluation); err != nil {
		return immunizationEvaluation, err
	}
	return immunizationEvaluation, nil
}
