// Copyright 2022 - Fasten Health
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir401

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
)

// THIS FILE IS GENERATED BY https://github.com/fastenhealth/gofhir-models-gen
// PLEASE DO NOT EDIT BY HAND

// Organization is documented here http://hl7.org/fhir/StructureDefinition/Organization
// A formally or informally recognized grouping of people or organizations formed for the purpose of achieving some form of collective action.  Includes companies, institutions, corporations, departments, community groups, healthcare practice groups, payer/insurer, etc.
type Organization struct {
	Unknown           map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                `bson:"id,omitempty" json:"id,omitempty"`
	Meta              *Meta                  `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules     *string                `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language          *string                `bson:"language,omitempty" json:"language,omitempty"`
	Text              *Narrative             `bson:"text,omitempty" json:"text,omitempty"`
	Contained         []jsontext.Value       `bson:"contained,omitempty" json:"contained,omitempty"`
	Extension         []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identifier        []Identifier           `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Active            *Boolean               `bson:"active,omitempty" json:"active,omitempty"`
	Type              []CodeableConcept      `bson:"type,omitempty" json:"type,omitempty"`
	Name              *string                `bson:"name,omitempty" json:"name,omitempty"`
	Alias             []string               `bson:"alias,omitempty" json:"alias,omitempty"`
	Telecom           []ContactPoint         `bson:"telecom,omitempty" json:"telecom,omitempty"`
	Address           []Address              `bson:"address,omitempty" json:"address,omitempty"`
	PartOf            *Reference             `bson:"partOf,omitempty" json:"partOf,omitempty"`
	Contact           []OrganizationContact  `bson:"contact,omitempty" json:"contact,omitempty"`
	Endpoint          []Reference            `bson:"endpoint,omitempty" json:"endpoint,omitempty"`
}

// Contact for the organization for a certain purpose.
// Where multiple contacts for the same purpose are provided there is a standard extension that can be used to determine which one is the preferred contact to use.
type OrganizationContact struct {
	Unknown           map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                `bson:"id,omitempty" json:"id,omitempty"`
	Extension         []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Purpose           *CodeableConcept       `bson:"purpose,omitempty" json:"purpose,omitempty"`
	Name              *HumanName             `bson:"name,omitempty" json:"name,omitempty"`
	Telecom           []ContactPoint         `bson:"telecom,omitempty" json:"telecom,omitempty"`
	Address           *Address               `bson:"address,omitempty" json:"address,omitempty"`
}

// This function returns resource reference information (resourceType, *resourceId)
func (r Organization) ResourceRef() (string, *string) {
	return "Organization", r.Id
}

// This function returns resources that are embedded in the resource
func (r Organization) ContainedResources() []jsontext.Value {
	return r.Contained
}

type OtherOrganization Organization

// MarshalJSON marshals the given Organization as JSON into a byte slice
// WARNING: must use a non-pointer receiver here, because non-pointer variables may not call this function otherwise
// See: https://groups.google.com/g/golang-nuts/c/gW53LC_ZC98
func (r Organization) MarshalJSON() ([]byte, error) {
	if r.Unknown == nil {
		r.Unknown = make(map[string]any)
	}
	r.Unknown["resourceType"] = "Organization"
	return v2.Marshal(OtherOrganization(r))
}

// UnmarshalOrganization unmarshals a Organization.
func UnmarshalOrganization(b []byte) (Organization, error) {
	var organization Organization
	if err := v2.Unmarshal(b, &organization); err != nil {
		return organization, err
	}
	return organization, nil
}
