// Copyright 2022 - Fasten Health
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir430

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
)

// THIS FILE IS GENERATED BY https://github.com/fastenhealth/gofhir-models-gen
// PLEASE DO NOT EDIT BY HAND

// DetectedIssue is documented here http://hl7.org/fhir/StructureDefinition/DetectedIssue
// Indicates an actual or potential clinical issue with or between one or more active or proposed clinical actions for a patient; e.g. Drug-drug interaction, Ineffective treatment frequency, Procedure-condition conflict, etc.
type DetectedIssue struct {
	Unknown            map[string]interface{}    `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                 *string                   `bson:"id,omitempty" json:"id,omitempty"`
	Meta               *Meta                     `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules      *string                   `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language           *string                   `bson:"language,omitempty" json:"language,omitempty"`
	Text               *Narrative                `bson:"text,omitempty" json:"text,omitempty"`
	Contained          []jsontext.Value          `bson:"contained,omitempty" json:"contained,omitempty"`
	Extension          []Extension               `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension  []Extension               `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identifier         []Identifier              `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Status             ObservationStatus         `bson:"status" json:"status"`
	Code               *CodeableConcept          `bson:"code,omitempty" json:"code,omitempty"`
	Severity           *DetectedIssueSeverity    `bson:"severity,omitempty" json:"severity,omitempty"`
	Patient            *Reference                `bson:"patient,omitempty" json:"patient,omitempty"`
	IdentifiedDateTime *string                   `bson:"identifiedDateTime,omitempty" json:"identifiedDateTime,omitempty"`
	IdentifiedPeriod   *Period                   `bson:"identifiedPeriod,omitempty" json:"identifiedPeriod,omitempty"`
	Author             *Reference                `bson:"author,omitempty" json:"author,omitempty"`
	Implicated         []Reference               `bson:"implicated,omitempty" json:"implicated,omitempty"`
	Evidence           []DetectedIssueEvidence   `bson:"evidence,omitempty" json:"evidence,omitempty"`
	Detail             *string                   `bson:"detail,omitempty" json:"detail,omitempty"`
	Reference          *string                   `bson:"reference,omitempty" json:"reference,omitempty"`
	Mitigation         []DetectedIssueMitigation `bson:"mitigation,omitempty" json:"mitigation,omitempty"`
}

// Supporting evidence or manifestations that provide the basis for identifying the detected issue such as a GuidanceResponse or MeasureReport.
type DetectedIssueEvidence struct {
	Unknown           map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                `bson:"id,omitempty" json:"id,omitempty"`
	Extension         []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Code              []CodeableConcept      `bson:"code,omitempty" json:"code,omitempty"`
	Detail            []Reference            `bson:"detail,omitempty" json:"detail,omitempty"`
}

// Indicates an action that has been taken or is committed to reduce or eliminate the likelihood of the risk identified by the detected issue from manifesting.  Can also reflect an observation of known mitigating factors that may reduce/eliminate the need for any action.
type DetectedIssueMitigation struct {
	Unknown           map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                `bson:"id,omitempty" json:"id,omitempty"`
	Extension         []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Action            CodeableConcept        `bson:"action" json:"action"`
	Date              *string                `bson:"date,omitempty" json:"date,omitempty"`
	Author            *Reference             `bson:"author,omitempty" json:"author,omitempty"`
}

// This function returns resource reference information (resourceType, *resourceId)
func (r DetectedIssue) ResourceRef() (string, *string) {
	return "DetectedIssue", r.Id
}

// This function returns resources that are embedded in the resource
func (r DetectedIssue) ContainedResources() []jsontext.Value {
	return r.Contained
}

type OtherDetectedIssue DetectedIssue

// MarshalJSON marshals the given DetectedIssue as JSON into a byte slice
// WARNING: must use a non-pointer receiver here, because non-pointer variables may not call this function otherwise
// See: https://groups.google.com/g/golang-nuts/c/gW53LC_ZC98
func (r DetectedIssue) MarshalJSON() ([]byte, error) {
	if r.Unknown == nil {
		r.Unknown = make(map[string]any)
	}
	r.Unknown["resourceType"] = "DetectedIssue"
	return v2.Marshal(OtherDetectedIssue(r))
}

// UnmarshalDetectedIssue unmarshals a DetectedIssue.
func UnmarshalDetectedIssue(b []byte) (DetectedIssue, error) {
	var detectedIssue DetectedIssue
	if err := v2.Unmarshal(b, &detectedIssue); err != nil {
		return detectedIssue, err
	}
	return detectedIssue, nil
}
