// Copyright 2022 - Fasten Health
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir430

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
)

// THIS FILE IS GENERATED BY https://github.com/fastenhealth/gofhir-models-gen
// PLEASE DO NOT EDIT BY HAND

// GuidanceResponse is documented here http://hl7.org/fhir/StructureDefinition/GuidanceResponse
// A guidance response is the formal response to a guidance request, including any output parameters returned by the evaluation, as well as the description of any proposed actions to be taken.
type GuidanceResponse struct {
	Unknown               map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                    *string                `bson:"id,omitempty" json:"id,omitempty"`
	Meta                  *Meta                  `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules         *string                `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language              *string                `bson:"language,omitempty" json:"language,omitempty"`
	Text                  *Narrative             `bson:"text,omitempty" json:"text,omitempty"`
	Contained             []jsontext.Value       `bson:"contained,omitempty" json:"contained,omitempty"`
	Extension             []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension     []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	RequestIdentifier     *Identifier            `bson:"requestIdentifier,omitempty" json:"requestIdentifier,omitempty"`
	Identifier            []Identifier           `bson:"identifier,omitempty" json:"identifier,omitempty"`
	ModuleUri             string                 `bson:"moduleUri" json:"moduleUri"`
	ModuleCanonical       string                 `bson:"moduleCanonical" json:"moduleCanonical"`
	ModuleCodeableConcept CodeableConcept        `bson:"moduleCodeableConcept" json:"moduleCodeableConcept"`
	Status                GuidanceResponseStatus `bson:"status" json:"status"`
	Subject               *Reference             `bson:"subject,omitempty" json:"subject,omitempty"`
	Encounter             *Reference             `bson:"encounter,omitempty" json:"encounter,omitempty"`
	OccurrenceDateTime    *string                `bson:"occurrenceDateTime,omitempty" json:"occurrenceDateTime,omitempty"`
	Performer             *Reference             `bson:"performer,omitempty" json:"performer,omitempty"`
	ReasonCode            []CodeableConcept      `bson:"reasonCode,omitempty" json:"reasonCode,omitempty"`
	ReasonReference       []Reference            `bson:"reasonReference,omitempty" json:"reasonReference,omitempty"`
	Note                  []Annotation           `bson:"note,omitempty" json:"note,omitempty"`
	EvaluationMessage     []Reference            `bson:"evaluationMessage,omitempty" json:"evaluationMessage,omitempty"`
	OutputParameters      *Reference             `bson:"outputParameters,omitempty" json:"outputParameters,omitempty"`
	Result                *Reference             `bson:"result,omitempty" json:"result,omitempty"`
	DataRequirement       []DataRequirement      `bson:"dataRequirement,omitempty" json:"dataRequirement,omitempty"`
}

// This function returns resource reference information (resourceType, *resourceId)
func (r GuidanceResponse) ResourceRef() (string, *string) {
	return "GuidanceResponse", r.Id
}

// This function returns resources that are embedded in the resource
func (r GuidanceResponse) ContainedResources() []jsontext.Value {
	return r.Contained
}

type OtherGuidanceResponse GuidanceResponse

// MarshalJSON marshals the given GuidanceResponse as JSON into a byte slice
// WARNING: must use a non-pointer receiver here, because non-pointer variables may not call this function otherwise
// See: https://groups.google.com/g/golang-nuts/c/gW53LC_ZC98
func (r GuidanceResponse) MarshalJSON() ([]byte, error) {
	if r.Unknown == nil {
		r.Unknown = make(map[string]any)
	}
	r.Unknown["resourceType"] = "GuidanceResponse"
	return v2.Marshal(OtherGuidanceResponse(r))
}

// UnmarshalGuidanceResponse unmarshals a GuidanceResponse.
func UnmarshalGuidanceResponse(b []byte) (GuidanceResponse, error) {
	var guidanceResponse GuidanceResponse
	if err := v2.Unmarshal(b, &guidanceResponse); err != nil {
		return guidanceResponse, err
	}
	return guidanceResponse, nil
}
