// Copyright 2022 - Fasten Health
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir430

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
)

// THIS FILE IS GENERATED BY https://github.com/fastenhealth/gofhir-models-gen
// PLEASE DO NOT EDIT BY HAND

// MedicinalProductIndication is documented here http://hl7.org/fhir/StructureDefinition/MedicinalProductIndication
// Indication for the Medicinal Product.
type MedicinalProductIndication struct {
	Unknown                 map[string]interface{}                   `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                      *string                                  `bson:"id,omitempty" json:"id,omitempty"`
	Meta                    *Meta                                    `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules           *string                                  `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language                *string                                  `bson:"language,omitempty" json:"language,omitempty"`
	Text                    *Narrative                               `bson:"text,omitempty" json:"text,omitempty"`
	Contained               []jsontext.Value                         `bson:"contained,omitempty" json:"contained,omitempty"`
	Extension               []Extension                              `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension       []Extension                              `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Subject                 []Reference                              `bson:"subject,omitempty" json:"subject,omitempty"`
	DiseaseSymptomProcedure *CodeableConcept                         `bson:"diseaseSymptomProcedure,omitempty" json:"diseaseSymptomProcedure,omitempty"`
	DiseaseStatus           *CodeableConcept                         `bson:"diseaseStatus,omitempty" json:"diseaseStatus,omitempty"`
	Comorbidity             []CodeableConcept                        `bson:"comorbidity,omitempty" json:"comorbidity,omitempty"`
	IntendedEffect          *CodeableConcept                         `bson:"intendedEffect,omitempty" json:"intendedEffect,omitempty"`
	Duration                *Quantity                                `bson:"duration,omitempty" json:"duration,omitempty"`
	OtherTherapy            []MedicinalProductIndicationOtherTherapy `bson:"otherTherapy,omitempty" json:"otherTherapy,omitempty"`
	UndesirableEffect       []Reference                              `bson:"undesirableEffect,omitempty" json:"undesirableEffect,omitempty"`
	Population              []Population                             `bson:"population,omitempty" json:"population,omitempty"`
}

// Information about the use of the medicinal product in relation to other therapies described as part of the indication.
type MedicinalProductIndicationOtherTherapy struct {
	Unknown                   map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                        *string                `bson:"id,omitempty" json:"id,omitempty"`
	Extension                 []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension         []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	TherapyRelationshipType   CodeableConcept        `bson:"therapyRelationshipType" json:"therapyRelationshipType"`
	MedicationCodeableConcept CodeableConcept        `bson:"medicationCodeableConcept" json:"medicationCodeableConcept"`
	MedicationReference       Reference              `bson:"medicationReference" json:"medicationReference"`
}

// This function returns resource reference information (resourceType, *resourceId)
func (r MedicinalProductIndication) ResourceRef() (string, *string) {
	return "MedicinalProductIndication", r.Id
}

// This function returns resources that are embedded in the resource
func (r MedicinalProductIndication) ContainedResources() []jsontext.Value {
	return r.Contained
}

type OtherMedicinalProductIndication MedicinalProductIndication

// MarshalJSON marshals the given MedicinalProductIndication as JSON into a byte slice
// WARNING: must use a non-pointer receiver here, because non-pointer variables may not call this function otherwise
// See: https://groups.google.com/g/golang-nuts/c/gW53LC_ZC98
func (r MedicinalProductIndication) MarshalJSON() ([]byte, error) {
	if r.Unknown == nil {
		r.Unknown = make(map[string]any)
	}
	r.Unknown["resourceType"] = "MedicinalProductIndication"
	return v2.Marshal(OtherMedicinalProductIndication(r))
}

// UnmarshalMedicinalProductIndication unmarshals a MedicinalProductIndication.
func UnmarshalMedicinalProductIndication(b []byte) (MedicinalProductIndication, error) {
	var medicinalProductIndication MedicinalProductIndication
	if err := v2.Unmarshal(b, &medicinalProductIndication); err != nil {
		return medicinalProductIndication, err
	}
	return medicinalProductIndication, nil
}
