// Copyright 2022 - Fasten Health
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir430

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/fastenhealth/gofhir-models-gen
// PLEASE DO NOT EDIT BY HAND

// PlanDefinition is documented here http://hl7.org/fhir/StructureDefinition/PlanDefinition
// This resource allows for the definition of various types of plans as a sharable, consumable, and executable artifact. The resource is general enough to support the description of a broad range of clinical artifacts such as clinical decision support rules, order sets and protocols.
type PlanDefinition struct {
	Id                *string                `bson:"id,omitempty" json:"id,omitempty"`
	Meta              *Meta                  `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules     *string                `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language          *string                `bson:"language,omitempty" json:"language,omitempty"`
	Text              *Narrative             `bson:"text,omitempty" json:"text,omitempty"`
	Extension         []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Url               *string                `bson:"url,omitempty" json:"url,omitempty"`
	Identifier        []Identifier           `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Version           *string                `bson:"version,omitempty" json:"version,omitempty"`
	Name              *string                `bson:"name,omitempty" json:"name,omitempty"`
	Title             *string                `bson:"title,omitempty" json:"title,omitempty"`
	Subtitle          *string                `bson:"subtitle,omitempty" json:"subtitle,omitempty"`
	Type              *CodeableConcept       `bson:"type,omitempty" json:"type,omitempty"`
	Status            PublicationStatus      `bson:"status" json:"status"`
	Experimental      *bool                  `bson:"experimental,omitempty" json:"experimental,omitempty"`
	Date              *string                `bson:"date,omitempty" json:"date,omitempty"`
	Publisher         *string                `bson:"publisher,omitempty" json:"publisher,omitempty"`
	Contact           []ContactDetail        `bson:"contact,omitempty" json:"contact,omitempty"`
	Description       *string                `bson:"description,omitempty" json:"description,omitempty"`
	UseContext        []UsageContext         `bson:"useContext,omitempty" json:"useContext,omitempty"`
	Jurisdiction      []CodeableConcept      `bson:"jurisdiction,omitempty" json:"jurisdiction,omitempty"`
	Purpose           *string                `bson:"purpose,omitempty" json:"purpose,omitempty"`
	Usage             *string                `bson:"usage,omitempty" json:"usage,omitempty"`
	Copyright         *string                `bson:"copyright,omitempty" json:"copyright,omitempty"`
	ApprovalDate      *string                `bson:"approvalDate,omitempty" json:"approvalDate,omitempty"`
	LastReviewDate    *string                `bson:"lastReviewDate,omitempty" json:"lastReviewDate,omitempty"`
	EffectivePeriod   *Period                `bson:"effectivePeriod,omitempty" json:"effectivePeriod,omitempty"`
	Topic             []CodeableConcept      `bson:"topic,omitempty" json:"topic,omitempty"`
	Author            []ContactDetail        `bson:"author,omitempty" json:"author,omitempty"`
	Editor            []ContactDetail        `bson:"editor,omitempty" json:"editor,omitempty"`
	Reviewer          []ContactDetail        `bson:"reviewer,omitempty" json:"reviewer,omitempty"`
	Endorser          []ContactDetail        `bson:"endorser,omitempty" json:"endorser,omitempty"`
	RelatedArtifact   []RelatedArtifact      `bson:"relatedArtifact,omitempty" json:"relatedArtifact,omitempty"`
	Library           []string               `bson:"library,omitempty" json:"library,omitempty"`
	Goal              []PlanDefinitionGoal   `bson:"goal,omitempty" json:"goal,omitempty"`
	Action            []PlanDefinitionAction `bson:"action,omitempty" json:"action,omitempty"`
}

// Goals that describe what the activities within the plan are intended to achieve. For example, weight loss, restoring an activity of daily living, obtaining herd immunity via immunization, meeting a process improvement objective, etc.
type PlanDefinitionGoal struct {
	Id                *string                    `bson:"id,omitempty" json:"id,omitempty"`
	Extension         []Extension                `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension                `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Category          *CodeableConcept           `bson:"category,omitempty" json:"category,omitempty"`
	Description       CodeableConcept            `bson:"description" json:"description"`
	Priority          *CodeableConcept           `bson:"priority,omitempty" json:"priority,omitempty"`
	Start             *CodeableConcept           `bson:"start,omitempty" json:"start,omitempty"`
	Addresses         []CodeableConcept          `bson:"addresses,omitempty" json:"addresses,omitempty"`
	Documentation     []RelatedArtifact          `bson:"documentation,omitempty" json:"documentation,omitempty"`
	Target            []PlanDefinitionGoalTarget `bson:"target,omitempty" json:"target,omitempty"`
}

// Indicates what should be done and within what timeframe.
type PlanDefinitionGoalTarget struct {
	Id                *string          `bson:"id,omitempty" json:"id,omitempty"`
	Extension         []Extension      `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension      `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Measure           *CodeableConcept `bson:"measure,omitempty" json:"measure,omitempty"`
	Due               *Duration        `bson:"due,omitempty" json:"due,omitempty"`
}

// An action or group of actions to be taken as part of the plan.
// Note that there is overlap between many of the elements defined here and the ActivityDefinition resource. When an ActivityDefinition is referenced (using the definition element), the overlapping elements in the plan override the content of the referenced ActivityDefinition unless otherwise documented in the specific elements. See the PlanDefinition resource for more detailed information.
type PlanDefinitionAction struct {
	Id                  *string                             `bson:"id,omitempty" json:"id,omitempty"`
	Extension           []Extension                         `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension   []Extension                         `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Prefix              *string                             `bson:"prefix,omitempty" json:"prefix,omitempty"`
	Title               *string                             `bson:"title,omitempty" json:"title,omitempty"`
	Description         *string                             `bson:"description,omitempty" json:"description,omitempty"`
	TextEquivalent      *string                             `bson:"textEquivalent,omitempty" json:"textEquivalent,omitempty"`
	Priority            *RequestPriority                    `bson:"priority,omitempty" json:"priority,omitempty"`
	Code                []CodeableConcept                   `bson:"code,omitempty" json:"code,omitempty"`
	Reason              []CodeableConcept                   `bson:"reason,omitempty" json:"reason,omitempty"`
	Documentation       []RelatedArtifact                   `bson:"documentation,omitempty" json:"documentation,omitempty"`
	GoalId              []string                            `bson:"goalId,omitempty" json:"goalId,omitempty"`
	Trigger             []TriggerDefinition                 `bson:"trigger,omitempty" json:"trigger,omitempty"`
	Condition           []PlanDefinitionActionCondition     `bson:"condition,omitempty" json:"condition,omitempty"`
	Input               []DataRequirement                   `bson:"input,omitempty" json:"input,omitempty"`
	Output              []DataRequirement                   `bson:"output,omitempty" json:"output,omitempty"`
	RelatedAction       []PlanDefinitionActionRelatedAction `bson:"relatedAction,omitempty" json:"relatedAction,omitempty"`
	Participant         []PlanDefinitionActionParticipant   `bson:"participant,omitempty" json:"participant,omitempty"`
	Type                *CodeableConcept                    `bson:"type,omitempty" json:"type,omitempty"`
	GroupingBehavior    *ActionGroupingBehavior             `bson:"groupingBehavior,omitempty" json:"groupingBehavior,omitempty"`
	SelectionBehavior   *ActionSelectionBehavior            `bson:"selectionBehavior,omitempty" json:"selectionBehavior,omitempty"`
	RequiredBehavior    *ActionRequiredBehavior             `bson:"requiredBehavior,omitempty" json:"requiredBehavior,omitempty"`
	PrecheckBehavior    *ActionPrecheckBehavior             `bson:"precheckBehavior,omitempty" json:"precheckBehavior,omitempty"`
	CardinalityBehavior *ActionCardinalityBehavior          `bson:"cardinalityBehavior,omitempty" json:"cardinalityBehavior,omitempty"`
	Transform           *string                             `bson:"transform,omitempty" json:"transform,omitempty"`
	DynamicValue        []PlanDefinitionActionDynamicValue  `bson:"dynamicValue,omitempty" json:"dynamicValue,omitempty"`
	Action              []PlanDefinitionAction              `bson:"action,omitempty" json:"action,omitempty"`
}

// An expression that describes applicability criteria or start/stop conditions for the action.
// When multiple conditions of the same kind are present, the effects are combined using AND semantics, so the overall condition is true only if all the conditions are true.
type PlanDefinitionActionCondition struct {
	Id                *string             `bson:"id,omitempty" json:"id,omitempty"`
	Extension         []Extension         `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension         `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Kind              ActionConditionKind `bson:"kind" json:"kind"`
	Expression        *Expression         `bson:"expression,omitempty" json:"expression,omitempty"`
}

// A relationship to another action such as "before" or "30-60 minutes after start of".
// When an action depends on multiple actions, the meaning is that all actions are dependencies, rather than that any of the actions are a dependency.
type PlanDefinitionActionRelatedAction struct {
	Id                *string                `bson:"id,omitempty" json:"id,omitempty"`
	Extension         []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	ActionId          string                 `bson:"actionId" json:"actionId"`
	Relationship      ActionRelationshipType `bson:"relationship" json:"relationship"`
}

// Indicates who should participate in performing the action described.
type PlanDefinitionActionParticipant struct {
	Id                *string               `bson:"id,omitempty" json:"id,omitempty"`
	Extension         []Extension           `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension           `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Type              ActionParticipantType `bson:"type" json:"type"`
	Role              *CodeableConcept      `bson:"role,omitempty" json:"role,omitempty"`
}

// Customizations that should be applied to the statically defined resource. For example, if the dosage of a medication must be computed based on the patient's weight, a customization would be used to specify an expression that calculated the weight, and the path on the resource that would contain the result.
// Dynamic values are applied in the order in which they are defined in the PlanDefinition resource. Note that when dynamic values are also specified by a referenced ActivityDefinition, the dynamicValues from the ActivityDefinition are applied first, followed by the dynamicValues specified here. In addition, if both a transform and dynamic values are specific, the dynamic values are applied to the result of the transform.
type PlanDefinitionActionDynamicValue struct {
	Id                *string     `bson:"id,omitempty" json:"id,omitempty"`
	Extension         []Extension `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Path              *string     `bson:"path,omitempty" json:"path,omitempty"`
	Expression        *Expression `bson:"expression,omitempty" json:"expression,omitempty"`
}

// This function returns resource reference information
func (r PlanDefinition) ResourceRef() (string, *string) {
	return "PlanDefinition", r.Id
}

type OtherPlanDefinition PlanDefinition

// MarshalJSON marshals the given PlanDefinition as JSON into a byte slice
func (r PlanDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherPlanDefinition
		ResourceType string `json:"resourceType"`
	}{
		OtherPlanDefinition: OtherPlanDefinition(r),
		ResourceType:        "PlanDefinition",
	})
}

// UnmarshalPlanDefinition unmarshals a PlanDefinition.
func UnmarshalPlanDefinition(b []byte) (PlanDefinition, error) {
	var planDefinition PlanDefinition
	if err := json.Unmarshal(b, &planDefinition); err != nil {
		return planDefinition, err
	}
	return planDefinition, nil
}
