// Copyright 2022 - Fasten Health
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir430

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
)

// THIS FILE IS GENERATED BY https://github.com/fastenhealth/gofhir-models-gen
// PLEASE DO NOT EDIT BY HAND

// Provenance is documented here http://hl7.org/fhir/StructureDefinition/Provenance
// Provenance of a resource is a record that describes entities and processes involved in producing and delivering or otherwise influencing that resource. Provenance provides a critical foundation for assessing authenticity, enabling trust, and allowing reproducibility. Provenance assertions are a form of contextual metadata and can themselves become important records with their own provenance. Provenance statement indicates clinical significance in terms of confidence in authenticity, reliability, and trustworthiness, integrity, and stage in lifecycle (e.g. Document Completion - has the artifact been legally authenticated), all of which may impact security, privacy, and trust policies.
type Provenance struct {
	Unknown           map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                `bson:"id,omitempty" json:"id,omitempty"`
	Meta              *Meta                  `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules     *string                `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language          *string                `bson:"language,omitempty" json:"language,omitempty"`
	Text              *Narrative             `bson:"text,omitempty" json:"text,omitempty"`
	Contained         []jsontext.Value       `bson:"contained,omitempty" json:"contained,omitempty"`
	Extension         []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Target            []Reference            `bson:"target" json:"target"`
	OccurredPeriod    *Period                `bson:"occurredPeriod,omitempty" json:"occurredPeriod,omitempty"`
	OccurredDateTime  *string                `bson:"occurredDateTime,omitempty" json:"occurredDateTime,omitempty"`
	Recorded          string                 `bson:"recorded" json:"recorded"`
	Policy            []string               `bson:"policy,omitempty" json:"policy,omitempty"`
	Location          *Reference             `bson:"location,omitempty" json:"location,omitempty"`
	Reason            []CodeableConcept      `bson:"reason,omitempty" json:"reason,omitempty"`
	Activity          *CodeableConcept       `bson:"activity,omitempty" json:"activity,omitempty"`
	Agent             []ProvenanceAgent      `bson:"agent" json:"agent"`
	Entity            []ProvenanceEntity     `bson:"entity,omitempty" json:"entity,omitempty"`
	Signature         []Signature            `bson:"signature,omitempty" json:"signature,omitempty"`
}

// An actor taking a role in an activity  for which it can be assigned some degree of responsibility for the activity taking place.
// Several agents may be associated (i.e. has some responsibility for an activity) with an activity and vice-versa.
type ProvenanceAgent struct {
	Unknown           map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                `bson:"id,omitempty" json:"id,omitempty"`
	Extension         []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Type              *CodeableConcept       `bson:"type,omitempty" json:"type,omitempty"`
	Role              []CodeableConcept      `bson:"role,omitempty" json:"role,omitempty"`
	Who               Reference              `bson:"who" json:"who"`
	OnBehalfOf        *Reference             `bson:"onBehalfOf,omitempty" json:"onBehalfOf,omitempty"`
}

// An entity used in this activity.
type ProvenanceEntity struct {
	Unknown           map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                `bson:"id,omitempty" json:"id,omitempty"`
	Extension         []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Role              ProvenanceEntityRole   `bson:"role" json:"role"`
	What              Reference              `bson:"what" json:"what"`
	Agent             []ProvenanceAgent      `bson:"agent,omitempty" json:"agent,omitempty"`
}

// This function returns resource reference information (resourceType, *resourceId)
func (r Provenance) ResourceRef() (string, *string) {
	return "Provenance", r.Id
}

// This function returns resources that are embedded in the resource
func (r Provenance) ContainedResources() []jsontext.Value {
	return r.Contained
}

type OtherProvenance Provenance

// MarshalJSON marshals the given Provenance as JSON into a byte slice
// WARNING: must use a non-pointer receiver here, because non-pointer variables may not call this function otherwise
// See: https://groups.google.com/g/golang-nuts/c/gW53LC_ZC98
func (r Provenance) MarshalJSON() ([]byte, error) {
	if r.Unknown == nil {
		r.Unknown = make(map[string]any)
	}
	r.Unknown["resourceType"] = "Provenance"
	return v2.Marshal(OtherProvenance(r))
}

// UnmarshalProvenance unmarshals a Provenance.
func UnmarshalProvenance(b []byte) (Provenance, error) {
	var provenance Provenance
	if err := v2.Unmarshal(b, &provenance); err != nil {
		return provenance, err
	}
	return provenance, nil
}
