// Copyright 2022 - Fasten Health
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir430

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
)

// THIS FILE IS GENERATED BY https://github.com/fastenhealth/gofhir-models-gen
// PLEASE DO NOT EDIT BY HAND

// RelatedPerson is documented here http://hl7.org/fhir/StructureDefinition/RelatedPerson
// Information about a person that is involved in the care for a patient, but who is not the target of healthcare, nor has a formal responsibility in the care process.
type RelatedPerson struct {
	Unknown           map[string]interface{}       `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                      `bson:"id,omitempty" json:"id,omitempty"`
	Meta              *Meta                        `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules     *string                      `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language          *string                      `bson:"language,omitempty" json:"language,omitempty"`
	Text              *Narrative                   `bson:"text,omitempty" json:"text,omitempty"`
	Contained         []jsontext.Value             `bson:"contained,omitempty" json:"contained,omitempty"`
	Extension         []Extension                  `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension                  `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identifier        []Identifier                 `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Active            *Boolean                     `bson:"active,omitempty" json:"active,omitempty"`
	Patient           Reference                    `bson:"patient" json:"patient"`
	Relationship      []CodeableConcept            `bson:"relationship,omitempty" json:"relationship,omitempty"`
	Name              []HumanName                  `bson:"name,omitempty" json:"name,omitempty"`
	Telecom           []ContactPoint               `bson:"telecom,omitempty" json:"telecom,omitempty"`
	Gender            *AdministrativeGender        `bson:"gender,omitempty" json:"gender,omitempty"`
	BirthDate         *string                      `bson:"birthDate,omitempty" json:"birthDate,omitempty"`
	Address           []Address                    `bson:"address,omitempty" json:"address,omitempty"`
	Photo             []Attachment                 `bson:"photo,omitempty" json:"photo,omitempty"`
	Period            *Period                      `bson:"period,omitempty" json:"period,omitempty"`
	Communication     []RelatedPersonCommunication `bson:"communication,omitempty" json:"communication,omitempty"`
}

// A language which may be used to communicate with about the patient's health.
// If no language is specified, this *implies* that the default local language is spoken.  If you need to convey proficiency for multiple modes, then you need multiple RelatedPerson.Communication associations.   If the RelatedPerson does not speak the default local language, then the Interpreter Required Standard can be used to explicitly declare that an interpreter is required.
type RelatedPersonCommunication struct {
	Unknown           map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                `bson:"id,omitempty" json:"id,omitempty"`
	Extension         []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Language          CodeableConcept        `bson:"language" json:"language"`
	Preferred         *Boolean               `bson:"preferred,omitempty" json:"preferred,omitempty"`
}

// This function returns resource reference information (resourceType, *resourceId)
func (r RelatedPerson) ResourceRef() (string, *string) {
	return "RelatedPerson", r.Id
}

// This function returns resources that are embedded in the resource
func (r RelatedPerson) ContainedResources() []jsontext.Value {
	return r.Contained
}

type OtherRelatedPerson RelatedPerson

// MarshalJSON marshals the given RelatedPerson as JSON into a byte slice
// WARNING: must use a non-pointer receiver here, because non-pointer variables may not call this function otherwise
// See: https://groups.google.com/g/golang-nuts/c/gW53LC_ZC98
func (r RelatedPerson) MarshalJSON() ([]byte, error) {
	if r.Unknown == nil {
		r.Unknown = make(map[string]any)
	}
	r.Unknown["resourceType"] = "RelatedPerson"
	return v2.Marshal(OtherRelatedPerson(r))
}

// UnmarshalRelatedPerson unmarshals a RelatedPerson.
func UnmarshalRelatedPerson(b []byte) (RelatedPerson, error) {
	var relatedPerson RelatedPerson
	if err := v2.Unmarshal(b, &relatedPerson); err != nil {
		return relatedPerson, err
	}
	return relatedPerson, nil
}
