// Copyright 2022 - Fasten Health
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir430

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
)

// THIS FILE IS GENERATED BY https://github.com/fastenhealth/gofhir-models-gen
// PLEASE DO NOT EDIT BY HAND

// RiskAssessment is documented here http://hl7.org/fhir/StructureDefinition/RiskAssessment
// An assessment of the likely outcome(s) for a patient or other subject as well as the likelihood of each outcome.
type RiskAssessment struct {
	Unknown            map[string]interface{}     `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                 *string                    `bson:"id,omitempty" json:"id,omitempty"`
	Meta               *Meta                      `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules      *string                    `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language           *string                    `bson:"language,omitempty" json:"language,omitempty"`
	Text               *Narrative                 `bson:"text,omitempty" json:"text,omitempty"`
	Contained          []jsontext.Value           `bson:"contained,omitempty" json:"contained,omitempty"`
	Extension          []Extension                `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension  []Extension                `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identifier         []Identifier               `bson:"identifier,omitempty" json:"identifier,omitempty"`
	BasedOn            *Reference                 `bson:"basedOn,omitempty" json:"basedOn,omitempty"`
	Parent             *Reference                 `bson:"parent,omitempty" json:"parent,omitempty"`
	Status             ObservationStatus          `bson:"status" json:"status"`
	Method             *CodeableConcept           `bson:"method,omitempty" json:"method,omitempty"`
	Code               *CodeableConcept           `bson:"code,omitempty" json:"code,omitempty"`
	Subject            Reference                  `bson:"subject" json:"subject"`
	Encounter          *Reference                 `bson:"encounter,omitempty" json:"encounter,omitempty"`
	OccurrenceDateTime *string                    `bson:"occurrenceDateTime,omitempty" json:"occurrenceDateTime,omitempty"`
	OccurrencePeriod   *Period                    `bson:"occurrencePeriod,omitempty" json:"occurrencePeriod,omitempty"`
	Condition          *Reference                 `bson:"condition,omitempty" json:"condition,omitempty"`
	Performer          *Reference                 `bson:"performer,omitempty" json:"performer,omitempty"`
	ReasonCode         []CodeableConcept          `bson:"reasonCode,omitempty" json:"reasonCode,omitempty"`
	ReasonReference    []Reference                `bson:"reasonReference,omitempty" json:"reasonReference,omitempty"`
	Basis              []Reference                `bson:"basis,omitempty" json:"basis,omitempty"`
	Prediction         []RiskAssessmentPrediction `bson:"prediction,omitempty" json:"prediction,omitempty"`
	Mitigation         *string                    `bson:"mitigation,omitempty" json:"mitigation,omitempty"`
	Note               []Annotation               `bson:"note,omitempty" json:"note,omitempty"`
}

// Describes the expected outcome for the subject.
// Multiple repetitions can be used to identify the same type of outcome in different timeframes as well as different types of outcomes.
type RiskAssessmentPrediction struct {
	Unknown            map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                 *string                `bson:"id,omitempty" json:"id,omitempty"`
	Extension          []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension  []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Outcome            *CodeableConcept       `bson:"outcome,omitempty" json:"outcome,omitempty"`
	ProbabilityDecimal *jsontext.Value        `bson:"probabilityDecimal,omitempty" json:"probabilityDecimal,omitempty"`
	ProbabilityRange   *Range                 `bson:"probabilityRange,omitempty" json:"probabilityRange,omitempty"`
	QualitativeRisk    *CodeableConcept       `bson:"qualitativeRisk,omitempty" json:"qualitativeRisk,omitempty"`
	RelativeRisk       *jsontext.Value        `bson:"relativeRisk,omitempty" json:"relativeRisk,omitempty"`
	WhenPeriod         *Period                `bson:"whenPeriod,omitempty" json:"whenPeriod,omitempty"`
	WhenRange          *Range                 `bson:"whenRange,omitempty" json:"whenRange,omitempty"`
	Rationale          *string                `bson:"rationale,omitempty" json:"rationale,omitempty"`
}

// This function returns resource reference information (resourceType, *resourceId)
func (r RiskAssessment) ResourceRef() (string, *string) {
	return "RiskAssessment", r.Id
}

// This function returns resources that are embedded in the resource
func (r RiskAssessment) ContainedResources() []jsontext.Value {
	return r.Contained
}

type OtherRiskAssessment RiskAssessment

// MarshalJSON marshals the given RiskAssessment as JSON into a byte slice
// WARNING: must use a non-pointer receiver here, because non-pointer variables may not call this function otherwise
// See: https://groups.google.com/g/golang-nuts/c/gW53LC_ZC98
func (r RiskAssessment) MarshalJSON() ([]byte, error) {
	if r.Unknown == nil {
		r.Unknown = make(map[string]any)
	}
	r.Unknown["resourceType"] = "RiskAssessment"
	return v2.Marshal(OtherRiskAssessment(r))
}

// UnmarshalRiskAssessment unmarshals a RiskAssessment.
func UnmarshalRiskAssessment(b []byte) (RiskAssessment, error) {
	var riskAssessment RiskAssessment
	if err := v2.Unmarshal(b, &riskAssessment); err != nil {
		return riskAssessment, err
	}
	return riskAssessment, nil
}
