// Copyright 2022 - Fasten Health
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir430

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
)

// THIS FILE IS GENERATED BY https://github.com/fastenhealth/gofhir-models-gen
// PLEASE DO NOT EDIT BY HAND

// Schedule is documented here http://hl7.org/fhir/StructureDefinition/Schedule
// A container for slots of time that may be available for booking appointments.
type Schedule struct {
	Unknown           map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                `bson:"id,omitempty" json:"id,omitempty"`
	Meta              *Meta                  `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules     *string                `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language          *string                `bson:"language,omitempty" json:"language,omitempty"`
	Text              *Narrative             `bson:"text,omitempty" json:"text,omitempty"`
	Contained         []jsontext.Value       `bson:"contained,omitempty" json:"contained,omitempty"`
	Extension         []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identifier        []Identifier           `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Active            *Boolean               `bson:"active,omitempty" json:"active,omitempty"`
	ServiceCategory   []CodeableConcept      `bson:"serviceCategory,omitempty" json:"serviceCategory,omitempty"`
	ServiceType       []CodeableConcept      `bson:"serviceType,omitempty" json:"serviceType,omitempty"`
	Specialty         []CodeableConcept      `bson:"specialty,omitempty" json:"specialty,omitempty"`
	Actor             []Reference            `bson:"actor" json:"actor"`
	PlanningHorizon   *Period                `bson:"planningHorizon,omitempty" json:"planningHorizon,omitempty"`
	Comment           *string                `bson:"comment,omitempty" json:"comment,omitempty"`
}

// This function returns resource reference information (resourceType, *resourceId)
func (r Schedule) ResourceRef() (string, *string) {
	return "Schedule", r.Id
}

// This function returns resources that are embedded in the resource
func (r Schedule) ContainedResources() []jsontext.Value {
	return r.Contained
}

type OtherSchedule Schedule

// MarshalJSON marshals the given Schedule as JSON into a byte slice
// WARNING: must use a non-pointer receiver here, because non-pointer variables may not call this function otherwise
// See: https://groups.google.com/g/golang-nuts/c/gW53LC_ZC98
func (r Schedule) MarshalJSON() ([]byte, error) {
	if r.Unknown == nil {
		r.Unknown = make(map[string]any)
	}
	r.Unknown["resourceType"] = "Schedule"
	return v2.Marshal(OtherSchedule(r))
}

// UnmarshalSchedule unmarshals a Schedule.
func UnmarshalSchedule(b []byte) (Schedule, error) {
	var schedule Schedule
	if err := v2.Unmarshal(b, &schedule); err != nil {
		return schedule, err
	}
	return schedule, nil
}
