// Copyright 2022 - Fasten Health
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir430

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
)

// THIS FILE IS GENERATED BY https://github.com/fastenhealth/gofhir-models-gen
// PLEASE DO NOT EDIT BY HAND

// Slot is documented here http://hl7.org/fhir/StructureDefinition/Slot
// A slot of time on a schedule that may be available for booking appointments.
type Slot struct {
	Unknown           map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                `bson:"id,omitempty" json:"id,omitempty"`
	Meta              *Meta                  `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules     *string                `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language          *string                `bson:"language,omitempty" json:"language,omitempty"`
	Text              *Narrative             `bson:"text,omitempty" json:"text,omitempty"`
	Contained         []jsontext.Value       `bson:"contained,omitempty" json:"contained,omitempty"`
	Extension         []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identifier        []Identifier           `bson:"identifier,omitempty" json:"identifier,omitempty"`
	ServiceCategory   []CodeableConcept      `bson:"serviceCategory,omitempty" json:"serviceCategory,omitempty"`
	ServiceType       []CodeableConcept      `bson:"serviceType,omitempty" json:"serviceType,omitempty"`
	Specialty         []CodeableConcept      `bson:"specialty,omitempty" json:"specialty,omitempty"`
	AppointmentType   *CodeableConcept       `bson:"appointmentType,omitempty" json:"appointmentType,omitempty"`
	Schedule          Reference              `bson:"schedule" json:"schedule"`
	Status            SlotStatus             `bson:"status" json:"status"`
	Start             string                 `bson:"start" json:"start"`
	End               string                 `bson:"end" json:"end"`
	Overbooked        *Boolean               `bson:"overbooked,omitempty" json:"overbooked,omitempty"`
	Comment           *string                `bson:"comment,omitempty" json:"comment,omitempty"`
}

// This function returns resource reference information (resourceType, *resourceId)
func (r Slot) ResourceRef() (string, *string) {
	return "Slot", r.Id
}

// This function returns resources that are embedded in the resource
func (r Slot) ContainedResources() []jsontext.Value {
	return r.Contained
}

type OtherSlot Slot

// MarshalJSON marshals the given Slot as JSON into a byte slice
// WARNING: must use a non-pointer receiver here, because non-pointer variables may not call this function otherwise
// See: https://groups.google.com/g/golang-nuts/c/gW53LC_ZC98
func (r Slot) MarshalJSON() ([]byte, error) {
	if r.Unknown == nil {
		r.Unknown = make(map[string]any)
	}
	r.Unknown["resourceType"] = "Slot"
	return v2.Marshal(OtherSlot(r))
}

// UnmarshalSlot unmarshals a Slot.
func UnmarshalSlot(b []byte) (Slot, error) {
	var slot Slot
	if err := v2.Unmarshal(b, &slot); err != nil {
		return slot, err
	}
	return slot, nil
}
