// Copyright 2022 - Fasten Health
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir430

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
)

// THIS FILE IS GENERATED BY https://github.com/fastenhealth/gofhir-models-gen
// PLEASE DO NOT EDIT BY HAND

// Substance is documented here http://hl7.org/fhir/StructureDefinition/Substance
// A homogeneous material with a definite composition.
type Substance struct {
	Unknown           map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                `bson:"id,omitempty" json:"id,omitempty"`
	Meta              *Meta                  `bson:"meta,omitempty" json:"meta,omitempty"`
	ImplicitRules     *string                `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	Language          *string                `bson:"language,omitempty" json:"language,omitempty"`
	Text              *Narrative             `bson:"text,omitempty" json:"text,omitempty"`
	Contained         []jsontext.Value       `bson:"contained,omitempty" json:"contained,omitempty"`
	Extension         []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identifier        []Identifier           `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Status            *FHIRSubstanceStatus   `bson:"status,omitempty" json:"status,omitempty"`
	Category          []CodeableConcept      `bson:"category,omitempty" json:"category,omitempty"`
	Code              CodeableConcept        `bson:"code" json:"code"`
	Description       *string                `bson:"description,omitempty" json:"description,omitempty"`
	Instance          []SubstanceInstance    `bson:"instance,omitempty" json:"instance,omitempty"`
	Ingredient        []SubstanceIngredient  `bson:"ingredient,omitempty" json:"ingredient,omitempty"`
}

// Substance may be used to describe a kind of substance, or a specific package/container of the substance: an instance.
// If this element is not present, then the substance resource describes a kind of substance
type SubstanceInstance struct {
	Unknown           map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                *string                `bson:"id,omitempty" json:"id,omitempty"`
	Extension         []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Identifier        *Identifier            `bson:"identifier,omitempty" json:"identifier,omitempty"`
	Expiry            *string                `bson:"expiry,omitempty" json:"expiry,omitempty"`
	Quantity          *Quantity              `bson:"quantity,omitempty" json:"quantity,omitempty"`
}

// A substance can be composed of other substances.
type SubstanceIngredient struct {
	Unknown                  map[string]interface{} `json:",unknown"` // stores any unknown fields found during unmarshaling. See: https://pkg.go.dev/encoding/json/v2#example-package-UnknownMembers
	Id                       *string                `bson:"id,omitempty" json:"id,omitempty"`
	Extension                []Extension            `bson:"extension,omitempty" json:"extension,omitempty"`
	ModifierExtension        []Extension            `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	Quantity                 *Ratio                 `bson:"quantity,omitempty" json:"quantity,omitempty"`
	SubstanceCodeableConcept CodeableConcept        `bson:"substanceCodeableConcept" json:"substanceCodeableConcept"`
	SubstanceReference       Reference              `bson:"substanceReference" json:"substanceReference"`
}

// This function returns resource reference information (resourceType, *resourceId)
func (r Substance) ResourceRef() (string, *string) {
	return "Substance", r.Id
}

// This function returns resources that are embedded in the resource
func (r Substance) ContainedResources() []jsontext.Value {
	return r.Contained
}

type OtherSubstance Substance

// MarshalJSON marshals the given Substance as JSON into a byte slice
// WARNING: must use a non-pointer receiver here, because non-pointer variables may not call this function otherwise
// See: https://groups.google.com/g/golang-nuts/c/gW53LC_ZC98
func (r Substance) MarshalJSON() ([]byte, error) {
	if r.Unknown == nil {
		r.Unknown = make(map[string]any)
	}
	r.Unknown["resourceType"] = "Substance"
	return v2.Marshal(OtherSubstance(r))
}

// UnmarshalSubstance unmarshals a Substance.
func UnmarshalSubstance(b []byte) (Substance, error) {
	var substance Substance
	if err := v2.Unmarshal(b, &substance); err != nil {
		return substance, err
	}
	return substance, nil
}
